# Used by "mix format"
spark_locals_without_parens = [
  __identifier__: 1,
  action: 1,
  action: 2,
  action_type: 1,
  action_type: 2,
  autocomplete_option_label_key: 1,
  autocomplete_option_value_key: 1,
  autocomplete_search_action: 1,
  autocomplete_search_arg: 1,
  autofocus: 1,
  base_class: 2,
  base_class: 3,
  cell_class: 1,
  class: 1,
  column: 1,
  column: 2,
  default_display: 1,
  default_sort: 1,
  description: 1,
  exclude: 1,
  field: 1,
  field: 2,
  field_group: 1,
  field_group: 2,
  header_class: 1,
  input_class: 1,
  keyset_sortable?: 1,
  label: 1,
  options: 1,
  path: 1,
  prefix: 1,
  prefixed: 1,
  prompt: 1,
  render_cell_data: 1,
  sortable?: 1,
  source: 1,
  step: 1,
  step: 2,
  type: 1
]

[
  quokka: [autosort: [:map, :defstruct, :schema]],
  import_deps: [:ash, :hologram],
  locals_without_parens: spark_locals_without_parens,
  export: [locals_without_parens: spark_locals_without_parens],
  plugins: [Quokka, Phoenix.LiveView.HTMLFormatter, Spark.Formatter],
  inputs: ["*.{heex,ex,exs}", "{config,lib,test}/**/*.{heex,ex,exs}"]
]
